### ISSUE TITLE
Client does not work on mac

### ISSUE THREAD

**Issue by fspaniol** [SAP/InfraBox-cli#12]
When trying to run any command on MAC, I get the following:

```
 infrabox version
Traceback (most recent call last):
  File "/usr/local/bin/infrabox", line 2, in <module>
    import infraboxcli
  File "/usr/local/lib/python2.7/site-packages/infraboxcli/__init__.py", line 13, in <module>
    from infraboxcli.install import install_infrabox
  File "/usr/local/lib/python2.7/site-packages/infraboxcli/install.py", line 11, in <module>
    from halo import Halo
  File "/usr/local/lib/python2.7/site-packages/halo/__init__.py", line 7, in <module>
    from .halo import Halo
  File "/usr/local/lib/python2.7/site-packages/halo/halo.py", line 17, in <module>
    from halo._utils import is_supported, colored_frame, is_text_type, decode_utf_8_text, get_terminal_columns, \
  File "/usr/local/lib/python2.7/site-packages/halo/_utils.py", line 7, in <module>
    from backports.shutil_get_terminal_size import get_terminal_size
ImportError: No module named shutil_get_terminal_size
```

**Comment by fspaniol** [comment]
Tried on a different Mac and it appears to be working.
Seems like a dependency issue.
